### ISSUE TITLE
Picture is turned differently than the build-in Gallery app

### ISSUE THREAD

**Issue by VilleWitt** [pinniini/harbour-slideshow#7]
![20150117_002](https://cloud.githubusercontent.com/assets/522544/10363185/640aa138-6db3-11e5-8822-7727d0837951.jpg)

**Comment by pinniini** [comment]
Gallery app probably rotates the pictures base on EXIF-data(?) or something else. Slideshow just loads the images.

**Comment by VilleWitt** [comment]
Yeah, I think so too. But from the perspective of users, some pictures are shown rotated between the stock apps and harbour-slideshow.

**Comment by pinniini** [comment]
Yes, you are right, the inconsistency on image rotation between stock apps and harbour-slideshow should be resolved. Trying to figure a way to read the exif-data for the rotation.
